/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : bigint,
  'status' : string,
  'studentId' : bigint,
  'date' : string,
  'classId' : [] | [string],
}
export interface AuthResponse { 'token' : string, 'user' : UserAccount }
export interface Fee {
  'id' : bigint,
  'status' : string,
  'studentId' : bigint,
  'feeType' : string,
  'dueDate' : string,
  'description' : string,
  'collectedBy' : string,
  'paidDate' : [] | [string],
  'paidAmount' : bigint,
  'amount' : bigint,
}
export interface FeeSummary {
  'totalCollected' : bigint,
  'totalPending' : bigint,
  'byFeeType' : Array<[string, bigint, bigint]>,
}
export interface FeeType {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'defaultAmount' : bigint,
}
export interface GradeFeeAssignment {
  'id' : bigint,
  'dueDate' : string,
  'feeTypeId' : bigint,
  'grade' : string,
  'amount' : bigint,
}
export interface Homework {
  'id' : bigint,
  'title' : string,
  'postedBy' : Principal,
  'subject' : string,
  'dueDate' : string,
  'description' : string,
  'classId' : string,
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'postedBy' : Principal,
  'content' : string,
  'createdAt' : string,
}
export interface Result {
  'id' : bigint,
  'totalMarks' : number,
  'studentId' : bigint,
  'subject' : string,
  'marksObtained' : number,
  'grade' : string,
  'examName' : string,
}
export interface Stats {
  'totalStudents' : bigint,
  'pendingFees' : bigint,
  'totalNotices' : bigint,
}
export interface Student {
  'id' : bigint,
  'guardianContact' : string,
  'name' : string,
  'section' : string,
  'grade' : string,
  'rollNo' : bigint,
  'guardianName' : string,
}
export interface TimetableEntry {
  'id' : bigint,
  'startTime' : string,
  'subject' : string,
  'endTime' : string,
  'dayOfWeek' : string,
  'classId' : string,
  'teacherName' : string,
  'periodNum' : bigint,
}
export interface UserAccount {
  'id' : bigint,
  'username' : string,
  'displayName' : string,
  'role' : UserRole,
  'passwordHash' : string,
}
export interface UserProfile {
  'displayName' : string,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'teacher' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAttendance' : ActorMethod<
    [string, bigint, string, string, [] | [string]],
    bigint
  >,
  'addFee' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      bigint,
    ],
    bigint
  >,
  'addFeeType' : ActorMethod<[string, string, string, bigint], bigint>,
  'addHomework' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addNotice' : ActorMethod<[string, string, string, string], bigint>,
  'addResult' : ActorMethod<
    [string, bigint, string, string, number, number, string],
    bigint
  >,
  'addStudent' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    bigint
  >,
  'addTimetableEntry' : ActorMethod<
    [string, string, string, bigint, string, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignFeeToGrade' : ActorMethod<
    [string, string, bigint, bigint, string],
    bigint
  >,
  'createTeacherAccount' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'dashboardStats' : ActorMethod<[string], Stats>,
  'deleteFee' : ActorMethod<[string, bigint], undefined>,
  'deleteFeeType' : ActorMethod<[string, bigint], undefined>,
  'deleteStudent' : ActorMethod<[string, bigint], undefined>,
  'deleteTeacherAccount' : ActorMethod<[string, bigint], undefined>,
  'getAllFees' : ActorMethod<[string], Array<Fee>>,
  'getAllNotices' : ActorMethod<[string], Array<Notice>>,
  'getAllStudents' : ActorMethod<[string], Array<Student>>,
  'getAttendanceByClass' : ActorMethod<[string, string], Array<Attendance>>,
  'getAttendanceByStudent' : ActorMethod<[string, bigint], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCurrentUser' : ActorMethod<[string], [] | [UserAccount]>,
  'getFeeSummary' : ActorMethod<[string], FeeSummary>,
  'getFeeTypes' : ActorMethod<[string], Array<FeeType>>,
  'getFeesByStudent' : ActorMethod<[string, bigint], Array<Fee>>,
  'getGradeFeeAssignments' : ActorMethod<[string], Array<GradeFeeAssignment>>,
  'getHomeworkByClass' : ActorMethod<[string, string], Array<Homework>>,
  'getPendingFees' : ActorMethod<[string], Array<Fee>>,
  'getPendingFeesWithStudents' : ActorMethod<[string], Array<[Fee, string]>>,
  'getResultsByStudent' : ActorMethod<[string, bigint], Array<Result>>,
  'getStudent' : ActorMethod<[string, bigint], [] | [Student]>,
  'getTimetableByClass' : ActorMethod<[string, string], Array<TimetableEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTeachers' : ActorMethod<[string], Array<UserAccount>>,
  'login' : ActorMethod<[string, string], AuthResponse>,
  'logout' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[string], undefined>,
  'updateFee' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'updateFeeType' : ActorMethod<
    [string, bigint, string, string, bigint],
    undefined
  >,
  'updateStudent' : ActorMethod<
    [string, bigint, string, string, string, bigint, string, string],
    undefined
  >,
  'updateTeacherAccount' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];