/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Stats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'pendingFees' : IDL.Nat,
  'totalNotices' : IDL.Nat,
});
export const Fee = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
  'feeType' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'collectedBy' : IDL.Text,
  'paidDate' : IDL.Opt(IDL.Text),
  'paidAmount' : IDL.Int,
  'amount' : IDL.Int,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'content' : IDL.Text,
  'createdAt' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'guardianContact' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'grade' : IDL.Text,
  'rollNo' : IDL.Int,
  'guardianName' : IDL.Text,
});
export const Attendance = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'classId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
});
export const UserAccount = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : UserRole,
  'passwordHash' : IDL.Text,
});
export const FeeSummary = IDL.Record({
  'totalCollected' : IDL.Int,
  'totalPending' : IDL.Int,
  'byFeeType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int, IDL.Int)),
});
export const FeeType = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'defaultAmount' : IDL.Int,
});
export const GradeFeeAssignment = IDL.Record({
  'id' : IDL.Nat,
  'dueDate' : IDL.Text,
  'feeTypeId' : IDL.Nat,
  'grade' : IDL.Text,
  'amount' : IDL.Int,
});
export const Homework = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'subject' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'classId' : IDL.Text,
});
export const Result = IDL.Record({
  'id' : IDL.Nat,
  'totalMarks' : IDL.Float64,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'marksObtained' : IDL.Float64,
  'grade' : IDL.Text,
  'examName' : IDL.Text,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'classId' : IDL.Text,
  'teacherName' : IDL.Text,
  'periodNum' : IDL.Nat,
});
export const AuthResponse = IDL.Record({
  'token' : IDL.Text,
  'user' : UserAccount,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAttendance' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addFee' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'addFeeType' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'addHomework' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addNotice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addResult' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTimetableEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignFeeToGrade' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTeacherAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'dashboardStats' : IDL.Func([IDL.Text], [Stats], ['query']),
  'deleteFee' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteFeeType' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteTeacherAccount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllFees' : IDL.Func([IDL.Text], [IDL.Vec(Fee)], ['query']),
  'getAllNotices' : IDL.Func([IDL.Text], [IDL.Vec(Notice)], ['query']),
  'getAllStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getAttendanceByClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCurrentUser' : IDL.Func([IDL.Text], [IDL.Opt(UserAccount)], []),
  'getFeeSummary' : IDL.Func([IDL.Text], [FeeSummary], ['query']),
  'getFeeTypes' : IDL.Func([IDL.Text], [IDL.Vec(FeeType)], ['query']),
  'getFeesByStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Fee)], ['query']),
  'getGradeFeeAssignments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GradeFeeAssignment)],
      ['query'],
    ),
  'getHomeworkByClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Homework)],
      ['query'],
    ),
  'getPendingFees' : IDL.Func([IDL.Text], [IDL.Vec(Fee)], ['query']),
  'getPendingFeesWithStudents' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(Fee, IDL.Text))],
      ['query'],
    ),
  'getResultsByStudent' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Result)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getTimetableByClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTeachers' : IDL.Func([IDL.Text], [IDL.Vec(UserAccount)], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResponse], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([IDL.Text], [], []),
  'updateFee' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'updateFeeType' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'updateStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateTeacherAccount' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Stats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'pendingFees' : IDL.Nat,
    'totalNotices' : IDL.Nat,
  });
  const Fee = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
    'feeType' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'collectedBy' : IDL.Text,
    'paidDate' : IDL.Opt(IDL.Text),
    'paidAmount' : IDL.Int,
    'amount' : IDL.Int,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'content' : IDL.Text,
    'createdAt' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'guardianContact' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'grade' : IDL.Text,
    'rollNo' : IDL.Int,
    'guardianName' : IDL.Text,
  });
  const Attendance = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'classId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'teacher' : IDL.Null });
  const UserAccount = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : UserRole,
    'passwordHash' : IDL.Text,
  });
  const FeeSummary = IDL.Record({
    'totalCollected' : IDL.Int,
    'totalPending' : IDL.Int,
    'byFeeType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int, IDL.Int)),
  });
  const FeeType = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'defaultAmount' : IDL.Int,
  });
  const GradeFeeAssignment = IDL.Record({
    'id' : IDL.Nat,
    'dueDate' : IDL.Text,
    'feeTypeId' : IDL.Nat,
    'grade' : IDL.Text,
    'amount' : IDL.Int,
  });
  const Homework = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'subject' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'classId' : IDL.Text,
  });
  const Result = IDL.Record({
    'id' : IDL.Nat,
    'totalMarks' : IDL.Float64,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'marksObtained' : IDL.Float64,
    'grade' : IDL.Text,
    'examName' : IDL.Text,
  });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'classId' : IDL.Text,
    'teacherName' : IDL.Text,
    'periodNum' : IDL.Nat,
  });
  const AuthResponse = IDL.Record({ 'token' : IDL.Text, 'user' : UserAccount });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAttendance' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addFee' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'addFeeType' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addHomework' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addNotice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addResult' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTimetableEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignFeeToGrade' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTeacherAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'dashboardStats' : IDL.Func([IDL.Text], [Stats], ['query']),
    'deleteFee' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteFeeType' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteTeacherAccount' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllFees' : IDL.Func([IDL.Text], [IDL.Vec(Fee)], ['query']),
    'getAllNotices' : IDL.Func([IDL.Text], [IDL.Vec(Notice)], ['query']),
    'getAllStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getAttendanceByClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCurrentUser' : IDL.Func([IDL.Text], [IDL.Opt(UserAccount)], []),
    'getFeeSummary' : IDL.Func([IDL.Text], [FeeSummary], ['query']),
    'getFeeTypes' : IDL.Func([IDL.Text], [IDL.Vec(FeeType)], ['query']),
    'getFeesByStudent' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Fee)],
        ['query'],
      ),
    'getGradeFeeAssignments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GradeFeeAssignment)],
        ['query'],
      ),
    'getHomeworkByClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Homework)],
        ['query'],
      ),
    'getPendingFees' : IDL.Func([IDL.Text], [IDL.Vec(Fee)], ['query']),
    'getPendingFeesWithStudents' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(Fee, IDL.Text))],
        ['query'],
      ),
    'getResultsByStudent' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Result)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getTimetableByClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTeachers' : IDL.Func([IDL.Text], [IDL.Vec(UserAccount)], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResponse], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([IDL.Text], [], []),
    'updateFee' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'updateFeeType' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateTeacherAccount' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };