/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AuthResponse {
    token: string;
    user: UserAccount;
}
export interface Attendance {
    id: bigint;
    status: string;
    studentId: bigint;
    date: string;
    classId?: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Stats {
    totalStudents: bigint;
    pendingFees: bigint;
    totalNotices: bigint;
}
export interface UserAccount {
    id: bigint;
    username: string;
    displayName: string;
    role: UserRole;
    passwordHash: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TimetableEntry {
    id: bigint;
    startTime: string;
    subject: string;
    endTime: string;
    dayOfWeek: string;
    classId: string;
    teacherName: string;
    periodNum: bigint;
}
export interface Fee {
    id: bigint;
    status: string;
    studentId: bigint;
    feeType: string;
    dueDate: string;
    description: string;
    collectedBy: string;
    paidDate?: string;
    paidAmount: bigint;
    amount: bigint;
}
export interface Result {
    id: bigint;
    totalMarks: number;
    studentId: bigint;
    subject: string;
    marksObtained: number;
    grade: string;
    examName: string;
}
export interface GradeFeeAssignment {
    id: bigint;
    dueDate: string;
    feeTypeId: bigint;
    grade: string;
    amount: bigint;
}
export interface FeeType {
    id: bigint;
    name: string;
    description: string;
    defaultAmount: bigint;
}
export interface Notice {
    id: bigint;
    title: string;
    postedBy: Principal;
    content: string;
    createdAt: string;
}
export interface FeeSummary {
    totalCollected: bigint;
    totalPending: bigint;
    byFeeType: Array<[string, bigint, bigint]>;
}
export interface Homework {
    id: bigint;
    title: string;
    postedBy: Principal;
    subject: string;
    dueDate: string;
    description: string;
    classId: string;
}
export interface UserProfile {
    displayName: string;
    name: string;
    role: string;
}
export interface Student {
    id: bigint;
    guardianContact: string;
    name: string;
    section: string;
    grade: string;
    rollNo: bigint;
    guardianName: string;
}
export enum UserRole {
    admin = "admin",
    teacher = "teacher"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAttendance(token: string, studentId: bigint, date: string, status: string, classId: string | null): Promise<bigint>;
    addFee(token: string, studentId: bigint, amount: bigint, description: string, dueDate: string, paidDate: string | null, status: string, feeType: string, collectedBy: string, paidAmount: bigint): Promise<bigint>;
    addFeeType(token: string, name: string, description: string, defaultAmount: bigint): Promise<bigint>;
    addHomework(token: string, title: string, description: string, subject: string, classId: string, dueDate: string): Promise<bigint>;
    addNotice(token: string, title: string, content: string, createdAt: string): Promise<bigint>;
    addResult(token: string, studentId: bigint, subject: string, examName: string, marksObtained: number, totalMarks: number, grade: string): Promise<bigint>;
    addStudent(token: string, name: string, grade: string, section: string, rollNo: bigint, guardianName: string, guardianContact: string): Promise<bigint>;
    addTimetableEntry(token: string, classId: string, dayOfWeek: string, periodNum: bigint, subject: string, teacherName: string, startTime: string, endTime: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignFeeToGrade(token: string, grade: string, feeTypeId: bigint, amount: bigint, dueDate: string): Promise<bigint>;
    createTeacherAccount(adminToken: string, username: string, password: string, displayName: string): Promise<void>;
    dashboardStats(token: string): Promise<Stats>;
    deleteFee(token: string, id: bigint): Promise<void>;
    deleteFeeType(token: string, id: bigint): Promise<void>;
    deleteStudent(token: string, id: bigint): Promise<void>;
    deleteTeacherAccount(adminToken: string, targetUserId: bigint): Promise<void>;
    getAllFees(token: string): Promise<Array<Fee>>;
    getAllNotices(token: string): Promise<Array<Notice>>;
    getAllStudents(token: string): Promise<Array<Student>>;
    getAttendanceByClass(token: string, classId: string): Promise<Array<Attendance>>;
    getAttendanceByStudent(token: string, studentId: bigint): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCurrentUser(token: string): Promise<UserAccount | null>;
    getFeeSummary(token: string): Promise<FeeSummary>;
    getFeeTypes(token: string): Promise<Array<FeeType>>;
    getFeesByStudent(token: string, studentId: bigint): Promise<Array<Fee>>;
    getGradeFeeAssignments(token: string): Promise<Array<GradeFeeAssignment>>;
    getHomeworkByClass(token: string, classId: string): Promise<Array<Homework>>;
    getPendingFees(token: string): Promise<Array<Fee>>;
    getPendingFeesWithStudents(token: string): Promise<Array<[Fee, string]>>;
    getResultsByStudent(token: string, studentId: bigint): Promise<Array<Result>>;
    getStudent(token: string, id: bigint): Promise<Student | null>;
    getTimetableByClass(token: string, classId: string): Promise<Array<TimetableEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listTeachers(token: string): Promise<Array<UserAccount>>;
    login(username: string, password: string): Promise<AuthResponse>;
    logout(token: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedData(token: string): Promise<void>;
    updateFee(token: string, feeId: bigint, amount: bigint, description: string, dueDate: string, paidDate: string | null, status: string, feeType: string, collectedBy: string, paidAmount: bigint): Promise<void>;
    updateFeeType(token: string, id: bigint, name: string, description: string, defaultAmount: bigint): Promise<void>;
    updateStudent(token: string, id: bigint, name: string, grade: string, section: string, rollNo: bigint, guardianName: string, guardianContact: string): Promise<void>;
    updateTeacherAccount(adminToken: string, targetUserId: bigint, username: string, displayName: string): Promise<void>;
}
import type { Attendance as _Attendance, AuthResponse as _AuthResponse, Fee as _Fee, Student as _Student, UserAccount as _UserAccount, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAttendance(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAttendance(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAttendance(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addFee(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string | null, arg6: string, arg7: string, arg8: string, arg9: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFee(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFee(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async addFeeType(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeeType(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeeType(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addHomework(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHomework(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHomework(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addNotice(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addResult(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: number, arg5: number, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addTimetableEntry(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimetableEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimetableEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignFeeToGrade(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.assignFeeToGrade(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignFeeToGrade(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTeacherAccount(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacherAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacherAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async dashboardStats(arg0: string): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.dashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dashboardStats(arg0);
            return result;
        }
    }
    async deleteFee(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFee(arg0, arg1);
            return result;
        }
    }
    async deleteFeeType(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeeType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeeType(arg0, arg1);
            return result;
        }
    }
    async deleteStudent(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0, arg1);
            return result;
        }
    }
    async deleteTeacherAccount(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacherAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacherAccount(arg0, arg1);
            return result;
        }
    }
    async getAllFees(arg0: string): Promise<Array<Fee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFees(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFees(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotices(arg0: string): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices(arg0);
            return result;
        }
    }
    async getAllStudents(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents(arg0);
            return result;
        }
    }
    async getAttendanceByClass(arg0: string, arg1: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByClass(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByClass(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByStudent(arg0: string, arg1: bigint): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByStudent(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByStudent(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(arg0: string): Promise<UserAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeSummary(arg0: string): Promise<FeeSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeSummary(arg0);
            return result;
        }
    }
    async getFeeTypes(arg0: string): Promise<Array<FeeType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeTypes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeTypes(arg0);
            return result;
        }
    }
    async getFeesByStudent(arg0: string, arg1: bigint): Promise<Array<Fee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeesByStudent(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeesByStudent(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGradeFeeAssignments(arg0: string): Promise<Array<GradeFeeAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradeFeeAssignments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradeFeeAssignments(arg0);
            return result;
        }
    }
    async getHomeworkByClass(arg0: string, arg1: string): Promise<Array<Homework>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeworkByClass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeworkByClass(arg0, arg1);
            return result;
        }
    }
    async getPendingFees(arg0: string): Promise<Array<Fee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFees(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFees(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingFeesWithStudents(arg0: string): Promise<Array<[Fee, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFeesWithStudents(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFeesWithStudents(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResultsByStudent(arg0: string, arg1: bigint): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResultsByStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResultsByStudent(arg0, arg1);
            return result;
        }
    }
    async getStudent(arg0: string, arg1: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0, arg1);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0, arg1);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimetableByClass(arg0: string, arg1: string): Promise<Array<TimetableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetableByClass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetableByClass(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listTeachers(arg0: string): Promise<Array<UserAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<AuthResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_AuthResponse_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_AuthResponse_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData(arg0);
            return result;
        }
    }
    async updateFee(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string | null, arg6: string, arg7: string, arg8: string, arg9: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFee(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFee(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateFeeType(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeeType(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeeType(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateStudent(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateTeacherAccount(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacherAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacherAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Attendance_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendance): Attendance {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResponse_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResponse): AuthResponse {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Fee_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fee): Fee {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccount_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccount): UserAccount {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserAccount]): UserAccount | null {
    return value.length === 0 ? null : from_candid_UserAccount_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    studentId: bigint;
    feeType: string;
    dueDate: string;
    description: string;
    collectedBy: string;
    paidDate: [] | [string];
    paidAmount: bigint;
    amount: bigint;
}): {
    id: bigint;
    status: string;
    studentId: bigint;
    feeType: string;
    dueDate: string;
    description: string;
    collectedBy: string;
    paidDate?: string;
    paidAmount: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        studentId: value.studentId,
        feeType: value.feeType,
        dueDate: value.dueDate,
        description: value.description,
        collectedBy: value.collectedBy,
        paidDate: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.paidDate)),
        paidAmount: value.paidAmount,
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    studentId: bigint;
    date: string;
    classId: [] | [string];
}): {
    id: bigint;
    status: string;
    studentId: bigint;
    date: string;
    classId?: string;
} {
    return {
        id: value.id,
        status: value.status,
        studentId: value.studentId,
        date: value.date,
        classId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.classId))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    username: string;
    displayName: string;
    role: _UserRole;
    passwordHash: string;
}): {
    id: bigint;
    username: string;
    displayName: string;
    role: UserRole;
    passwordHash: string;
} {
    return {
        id: value.id,
        username: value.username,
        displayName: value.displayName,
        role: from_candid_UserRole_n24(_uploadFile, _downloadFile, value.role),
        passwordHash: value.passwordHash
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    user: _UserAccount;
}): {
    token: string;
    user: UserAccount;
} {
    return {
        token: value.token,
        user: from_candid_UserAccount_n22(_uploadFile, _downloadFile, value.user)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Fee, string]): [Fee, string] {
    return [
        from_candid_Fee_n12(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    teacher: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "teacher" in value ? UserRole.teacher : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fee>): Array<Fee> {
    return value.map((x)=>from_candid_Fee_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendance>): Array<Attendance> {
    return value.map((x)=>from_candid_Attendance_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Fee, string]>): Array<[Fee, string]> {
    return value.map((x)=>from_candid_tuple_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAccount>): Array<UserAccount> {
    return value.map((x)=>from_candid_UserAccount_n22(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole__1_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
